AMINOACIDOS_INFO = {
    'A': {
        'nombre': 'Alanina',
        'abreviatura': 'Ala',
        'codigo': 'A',
        'peso_molecular': 89.09,
        'tipo': 'No polar, alifático',
        'hidrofobicidad': 'Alta (1.8)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'Aminoácido no polar más simple. Es pequeño y hidrofóbico, se encuentra frecuentemente en el interior de las proteínas. Participa en el metabolismo de glucosa y en la síntesis de proteínas.',
        'donde_se_encuentra': 'Abundante en proteínas estructurales como colágeno y queratina. Presente en seda de araña (hasta 30% de composición). Común en regiones alfa-hélice de proteínas globulares.',
        'funcion_biologica': 'Regulación del metabolismo de glucosa, transferencia de aminoácidos entre tejidos, síntesis de carnosina.',
        'propiedades_quimicas': 'Cadena lateral: -CH₃. Punto isoeléctrico: 6.00. Poco reactivo, proporciona estabilidad estructural.',
        'enfermedades_relacionadas': 'Niveles elevados asociados a diabetes tipo 2 e hipertensión.'
    },
    'C': {
        'nombre': 'Cisteína',
        'abreviatura': 'Cys',
        'codigo': 'C',
        'peso_molecular': 121.16,
        'tipo': 'Polar, especial',
        'hidrofobicidad': 'Alta (2.5)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'Único aminoácido con grupo tiol (-SH). Forma puentes disulfuro entre cadenas proteicas, estabilizando la estructura terciaria y cuaternaria de las proteínas.',
        'donde_se_encuentra': 'Muy abundante en queratina (cabello, uñas, piel). Presente en enzimas con sitios activos de cisteína como proteasas y deshidrogenasas. Común en anticuerpos (puentes disulfuro).',
        'funcion_biologica': 'Formación de puentes disulfuro, detoxificación hepática (glutatión), antioxidante, síntesis de taurina y coenzima A.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-SH. Punto isoeléctrico: 5.07. Puede oxidarse formando cistina (puente disulfuro).',
        'enfermedades_relacionadas': 'Deficiencia rara. Asociada a cataratas, problemas hepáticos y síndrome de malabsorción.'
    },
    'D': {
        'nombre': 'Ácido Aspártico',
        'abreviatura': 'Asp',
        'codigo': 'D',
        'peso_molecular': 133.10,
        'tipo': 'Polar, ácido, cargado negativamente',
        'hidrofobicidad': 'Baja (-3.5)',
        'carga': 'Negativa (-1 a pH fisiológico)',
        'esencial': False,
        'descripcion': 'Aminoácido ácido con grupo carboxilo en la cadena lateral. Importante en sitios activos de enzimas y en la unión de iones metálicos.',
        'donde_se_encuentra': 'Presente en sitios activos de muchas enzimas (aspartil proteasas). Abundante en proteínas de superficie celular y receptores. Común en regiones de unión a calcio.',
        'funcion_biologica': 'Participa en el ciclo de la urea, síntesis de purinas y pirimidinas, neurotransmisor excitatorio, precursor de asparagina.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-COOH. Punto isoeléctrico: 2.77. pKa de cadena lateral: 3.65.',
        'enfermedades_relacionadas': 'Niveles alterados en enfermedades neurodegenerativas y epilepsia.'
    },
    'E': {
        'nombre': 'Ácido Glutámico',
        'abreviatura': 'Glu',
        'codigo': 'E',
        'peso_molecular': 147.13,
        'tipo': 'Polar, ácido, cargado negativamente',
        'hidrofobicidad': 'Baja (-3.5)',
        'carga': 'Negativa (-1 a pH fisiológico)',
        'esencial': False,
        'descripcion': 'Aminoácido ácido más abundante en proteínas. Principal neurotransmisor excitatorio del sistema nervioso central.',
        'donde_se_encuentra': 'Muy abundante en proteínas del cerebro y sistema nervioso. Presente en gluten del trigo (hasta 40% de gliadina). Común en proteínas de almacenamiento de semillas.',
        'funcion_biologica': 'Neurotransmisor excitatorio principal, precursor de GABA (inhibitorio), detoxificación de amonio en cerebro, componente del glutatión.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-CH₂-COOH. Punto isoeléctrico: 3.22. pKa de cadena lateral: 4.25.',
        'enfermedades_relacionadas': 'Excitotoxicidad en Alzheimer, ELA y Parkinson. Monosodio de glutamato (MSG) como potenciador de sabor.'
    },
    'F': {
        'nombre': 'Fenilalanina',
        'abreviatura': 'Phe',
        'codigo': 'F',
        'peso_molecular': 165.19,
        'tipo': 'No polar, aromático',
        'hidrofobicidad': 'Alta (2.8)',
        'carga': 'Neutra',
        'esencial': True,
        'descripcion': 'Aminoácido esencial aromático. Precursor de tirosina, dopamina, noradrenalina y adrenalina. Absorbe luz UV a 257 nm.',
        'donde_se_encuentra': 'Abundante en proteínas de membrana y regiones hidrofóbicas. Presente en endorfinas y encefalinas. Común en sitios de unión a sustratos aromáticos.',
        'funcion_biologica': 'Precursor de neurotransmisores catecolaminas, síntesis de melanina, producción de hormonas tiroideas.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-C₆H₅. Punto isoeléctrico: 5.48. Absorbe luz UV (257 nm). Aromático e hidrofóbico.',
        'enfermedades_relacionadas': 'Fenilcetonuria (PKU): incapacidad de metabolizar fenilalanina, causa retraso mental si no se trata.'
    },
    'G': {
        'nombre': 'Glicina',
        'abreviatura': 'Gly',
        'codigo': 'G',
        'peso_molecular': 75.07,
        'tipo': 'No polar, especial (más pequeño)',
        'hidrofobicidad': 'Neutral (-0.4)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'El aminoácido más simple y pequeño. Único sin carbono quiral. Proporciona gran flexibilidad conformacional a las proteínas.',
        'donde_se_encuentra': 'Muy abundante en colágeno (hasta 33% de residuos). Presente en seda de araña. Común en giros beta y bucles de proteínas globulares.',
        'funcion_biologica': 'Neurotransmisor inhibidor en médula espinal y tronco cerebral, precursor de porfirinas (grupo hemo), síntesis de creatina y ácido biliar.',
        'propiedades_quimicas': 'Cadena lateral: -H. Punto isoeléctrico: 5.97. Sin isómeros D/L. Permite giros cerrados en la cadena polipeptídica.',
        'enfermedades_relacionadas': 'Hiperglicinemia no cetósica: convulsiones y encefalopatía severa.'
    },
    'H': {
        'nombre': 'Histidina',
        'abreviatura': 'His',
        'codigo': 'H',
        'peso_molecular': 155.16,
        'tipo': 'Polar, aromático, básico',
        'hidrofobicidad': 'Baja (-3.2)',
        'carga': 'Parcialmente positiva (pKa ~6.0)',
        'esencial': True,
        'descripcion': 'Aminoácido con imidazol en la cadena lateral, que le confiere capacidad de actuar como base y ácido a pH cercano al fisiológico. Esencial en catálisis enzimática.',
        'donde_se_encuentra': 'Presente en sitios activos de muchas enzimas (serín proteasas, quimotripsina). Abundante en hemoglobina y mioglobina. Común en proteínas de unión a metales.',
        'funcion_biologica': 'Residuo catalítico en enzimas, tamponador a pH fisiológico, precursor de histamina, unión de iones metálicos (Zn²⁺, Cu²⁺).',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-imidazol. Punto isoeléctrico: 7.59. pKa de imidazol: 6.0. Absorbe UV a 211 nm.',
        'enfermedades_relacionadas': 'Histidinemia (benigna). Deficiencia asociada a anemia y disfunción renal.'
    },
    'I': {
        'nombre': 'Isoleucina',
        'abreviatura': 'Ile',
        'codigo': 'I',
        'peso_molecular': 131.17,
        'tipo': 'No polar, alifático, ramificado',
        'hidrofobicidad': 'Muy alta (4.5)',
        'carga': 'Neutra',
        'esencial': True,
        'descripcion': 'Aminoácido esencial de cadena ramificada (BCAA). Muy hidrofóbico, se encuentra en el interior de proteínas globulares.',
        'donde_se_encuentra': 'Abundante en proteínas de músculo esquelético. Presente en hemoglobina. Común en regiones de lámina beta y núcleo hidrofóbico de proteínas.',
        'funcion_biologica': 'Metabolismo energético muscular, regulación de glucosa, síntesis proteica, señalización mTOR.',
        'propiedades_quimicas': 'Cadena lateral: -CH(CH₃)-CH₂-CH₃. Punto isoeléctrico: 6.02. Es el isómero de leucina con quiralidad en Cβ.',
        'enfermedades_relacionadas': 'Enfermedad de orina de jarabe de arce: deficiencia en degradación de BCAA, potencialmente letal.'
    },
    'K': {
        'nombre': 'Lisina',
        'abreviatura': 'Lys',
        'codigo': 'K',
        'peso_molecular': 146.19,
        'tipo': 'Polar, básico, cargado positivamente',
        'hidrofobicidad': 'Baja (-3.9)',
        'carga': 'Positiva (+1 a pH fisiológico)',
        'esencial': True,
        'descripcion': 'Aminoácido esencial con la cadena alifática más larga entre los básicos. Importante en unión de ADN, estabilización de proteínas y modificaciones postraduccionales.',
        'donde_se_encuentra': 'Abundante en histonas (unión al ADN). Presente en colágeno (hidroxilisina). Común en la superficie de proteínas, interactuando con fosfatos de ADN/RNA.',
        'funcion_biologica': 'Unión ADN-proteína, ubiquitinación (marcador de degradación), metilación (regulación epigenética), acilación (anclaje de membrana).',
        'propiedades_quimicas': 'Cadena lateral: -(CH₂)₄-NH₂. Punto isoeléctrico: 9.74. pKa de ε-amino: 10.53. Reacciona con grupo aldehído.',
        'enfermedades_relacionadas': 'Deficiencia asociada a fatiga, náuseas y problemas de crecimiento. Usada en suplementos para herpes.'
    },
    'L': {
        'nombre': 'Leucina',
        'abreviatura': 'Leu',
        'codigo': 'L',
        'peso_molecular': 131.17,
        'tipo': 'No polar, alifático, ramificado',
        'hidrofobicidad': 'Muy alta (3.8)',
        'carga': 'Neutra',
        'esencial': True,
        'descripcion': 'El aminoácido más abundante en proteínas. BCAA esencial, clave en la señalización mTOR para la síntesis proteica muscular.',
        'donde_se_encuentra': 'El más abundante en proteínas (~9% de todos los residuos). Muy común en láminas beta y hélices alfa del núcleo hidrofóbico. Presente en leucinas con cremallera (dimerización de factores de transcripción).',
        'funcion_biologica': 'Activador de mTOR (crecimiento muscular), regulación de glucosa, producción de energía en músculo, precursor de HMG-CoA (colesterol).',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-CH(CH₃)₂. Punto isoeléctrico: 5.98. Codificado por 6 codones (el más degenerado).',
        'enfermedades_relacionadas': 'Enfermedad de orina de jarabe de arce. Suplementación en desnutrición y sarcopenia.'
    },
    'M': {
        'nombre': 'Metionina',
        'abreviatura': 'Met',
        'codigo': 'M',
        'peso_molecular': 149.21,
        'tipo': 'No polar, azufrado',
        'hidrofobicidad': 'Alta (1.9)',
        'carga': 'Neutra',
        'esencial': True,
        'descripcion': 'Aminoácido esencial azufrado. Siempre el primer aminoácido en la traducción (codón AUG). Donante de grupos metilo vía S-adenosilmetionina (SAM).',
        'donde_se_encuentra': 'Presente en el inicio de toda proteína naciente. Abundante en proteínas de membrana. Común en regiones de interacción proteica.',
        'funcion_biologica': 'Inicio de traducción, metilación de ADN/proteínas/lípidos (vía SAM), precursor de cisteína, antioxidante, metabolismo de lípidos.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-CH₂-S-CH₃. Punto isoeléctrico: 5.74. Único codón (AUG). Se oxida a metionina-sulfóxido.',
        'enfermedades_relacionadas': 'Niveles elevados asociados a enfermedades cardiovasculares y ateroesclerosis (homocisteína).'
    },
    'N': {
        'nombre': 'Asparagina',
        'abreviatura': 'Asn',
        'codigo': 'N',
        'peso_molecular': 132.12,
        'tipo': 'Polar, no cargado',
        'hidrofobicidad': 'Baja (-3.5)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'Aminoácido polar con grupo amida. Sitio común de glicosilación N-ligada en proteínas de superficie y secretadas.',
        'donde_se_encuentra': 'Muy común en sitios de N-glicosilación (Asn-X-Ser/Thr). Abundante en proteínas de superficie celular y anticuerpos. Presente en látex de algunas plantas.',
        'funcion_biologica': 'N-glicosilación (plegamiento y estabilidad de proteínas), síntesis de ácido aspártico, participación en el ciclo de la urea.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-CONH₂. Punto isoeléctrico: 5.41. Sitio de desamidación espontánea (marcador de envejecimiento proteico).',
        'enfermedades_relacionadas': 'Asparaginasa usada como tratamiento en leucemia linfoblástica aguda (depleta asparagina).'
    },
    'P': {
        'nombre': 'Prolina',
        'abreviatura': 'Pro',
        'codigo': 'P',
        'peso_molecular': 115.13,
        'tipo': 'No polar, especial (iminoácido)',
        'hidrofobicidad': 'Baja (-1.6)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'El único iminoácido estándar. Su anillo pirrolidina restringe la rotación de la cadena principal, creando giros y curvas en las proteínas. Rompe hélices alfa.',
        'donde_se_encuentra': 'Muy abundante en colágeno (hasta 25%, como hidroxiprolina). Presente en giros beta y bucles de proteínas globulares. Común en regiones de unión de receptores.',
        'funcion_biologica': 'Estructural en colágeno, induce giros en la cadena polipeptídica, regulación de estabilidad de hélices alfa, hidroxilación dependiente de vitamina C.',
        'propiedades_quimicas': 'Cadena lateral: anillo pirrolidina (iminoácido). Punto isoeléctrico: 6.30. Restringe ángulo φ a ~-60°. Rompe hélices alfa.',
        'enfermedades_relacionadas': 'Deficiencia de vitamina C impide hidroxilación de prolina → escorbuto (colágeno defectuoso).'
    },
    'Q': {
        'nombre': 'Glutamina',
        'abreviatura': 'Gln',
        'codigo': 'Q',
        'peso_molecular': 146.15,
        'tipo': 'Polar, no cargado',
        'hidrofobicidad': 'Baja (-3.5)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'Aminoácido polar más abundante en el cuerpo. Principal transportador de nitrógeno entre tejidos. Esencial para células de rápido crecimiento (inmunitarias, intestinales).',
        'donde_se_encuentra': 'Muy abundante en proteínas del cerebro. Presente en músculo esquelético (almacén de nitrógeno). Común en proteínas de trigo (gliadina).',
        'funcion_biologica': 'Transporte de nitrógeno, síntesis de nucleótidos, sustrato energético de enterocitos e inmunocitos, precursor de glutamato y GABA.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-CH₂-CONH₂. Punto isoeléctrico: 5.65. Se desamida a glutamato (marcador de envejecimiento).',
        'enfermedades_relacionadas': 'Deficiencia en estrés metabólico severo (quemaduras, sepsis). Usada como suplemento en cáncer y enfermedades intestinales.'
    },
    'R': {
        'nombre': 'Arginina',
        'abreviatura': 'Arg',
        'codigo': 'R',
        'peso_molecular': 174.20,
        'tipo': 'Polar, básico, cargado positivamente',
        'hidrofobicidad': 'Muy baja (-4.5)',
        'carga': 'Positiva (+1 a pH fisiológico)',
        'esencial': False,
        'descripcion': 'Aminoácido básico con el grupo guanidino más fuerte en proteínas (pKa 12.5). Siempre cargado a pH fisiológico. Esencial en la unión a ADN y fosfatos.',
        'donde_se_encuentra': 'Muy abundante en histonas y proteínas de unión a ADN. Presente en sitios activos de enzimas (tripsina). Común en canales iónicos y receptores.',
        'funcion_biologica': 'Precursor de óxido nítrico (vasodilatación), ciclo de la urea, síntesis de creatina, síntesis de agmatina, regeneración de tejidos.',
        'propiedades_quimicas': 'Cadena lateral: -(CH₂)₃-NH-C(=NH)-NH₂. Punto isoeléctrico: 10.76. pKa de guanidino: 12.48. Forma puentes de hidrógeno múltiples.',
        'enfermedades_relacionadas': 'Deficiencia en prematuros y estrés catabólico. Usada en enfermedades cardiovasculares y disfunción eréctil.'
    },
    'S': {
        'nombre': 'Serina',
        'abreviatura': 'Ser',
        'codigo': 'S',
        'peso_molecular': 105.09,
        'tipo': 'Polar, no cargado',
        'hidrofobicidad': 'Baja (-0.8)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'Aminoácido polar con grupo hidroxilo. Sitio principal de fosforilación en señalización celular. Participa en catálisis enzimática (tríada catalítica).',
        'donde_se_encuentra': 'Muy común en sitios activos de enzimas (serín proteasas: tripsina, quimotripsina). Abundante en fosfoglicoproteínas de membrana. Presente en sitios de O-glicosilación.',
        'funcion_biologica': 'Fosforilación (señalización celular), catálisis enzimática (tríada Ser-His-Asp), O-glicosilación, síntesis de esfingolípidos y folato.',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-OH. Punto isoeléctrico: 5.68. Reactivo, forma puentes de hidrógeno. Sitio de fosforilación por quinasas.',
        'enfermedades_relacionadas': 'Deficiencia de serina palmitoiltransferasa → neuropatía sensorial hereditaria.'
    },
    'T': {
        'nombre': 'Treonina',
        'abreviatura': 'Thr',
        'codigo': 'T',
        'peso_molecular': 119.12,
        'tipo': 'Polar, no cargado',
        'hidrofobicidad': 'Baja (-0.7)',
        'carga': 'Neutra',
        'esencial': True,
        'descripcion': 'Aminoácido esencial con grupo hidroxilo. Segundo sitio más común de fosforilación. Único aminoácido esencial que es ambas cosas: polar y con hidroxilo.',
        'donde_se_encuentra': 'Presente en sitios de fosforilación (junto con serina y tirosina). Abundante en mucinas (proteínas de mucosidad). Común en receptores de superficie celular.',
        'funcion_biologica': 'Fosforilación (señalización), O-glicosilación, síntesis de glicina, metabolismo de lípidos, función inmunitaria.',
        'propiedades_quimicas': 'Cadena lateral: -CH(OH)-CH₃. Punto isoeléctrico: 5.60. Tiene dos centros quirales. Forma puentes de hidrógeno.',
        'enfermedades_relacionadas': 'Deficiencia asociada a disfunción hepática y problemas de crecimiento.'
    },
    'V': {
        'nombre': 'Valina',
        'abreviatura': 'Val',
        'codigo': 'V',
        'peso_molecular': 117.15,
        'tipo': 'No polar, alifático, ramificado',
        'hidrofobicidad': 'Muy alta (4.2)',
        'carga': 'Neutra',
        'esencial': True,
        'descripcion': 'Aminoácido esencial de cadena ramificada (BCAA). Muy hidrofóbico, importante en el empaquetamiento del núcleo de proteínas globulares.',
        'donde_se_encuentra': 'Abundante en el núcleo hidrofóbico de proteínas globulares. Presente en proteínas de músculo. Común en láminas beta y regiones de interacción proteica.',
        'funcion_biologica': 'Metabolismo energético muscular, síntesis proteica, regulación de glucosa, participación en vía de señalización mTOR.',
        'propiedades_quimicas': 'Cadena lateral: -CH(CH₃)₂. Punto isoeléctrico: 5.96. Cadena ramificada similar a isoleucina y leucina.',
        'enfermedades_relacionadas': 'Enfermedad de orina de jarabe de arce. Suplementación en desnutrición y enfermedades hepáticas.'
    },
    'W': {
        'nombre': 'Triptófano',
        'abreviatura': 'Trp',
        'codigo': 'W',
        'peso_molecular': 204.23,
        'tipo': 'No polar, aromático',
        'hidrofobicidad': 'Baja (-0.9)',
        'carga': 'Neutra',
        'esencial': True,
        'descripcion': 'El aminoácido más grande y menos abundante. Aromático con indol. Absorbe luz UV fuertemente a 280 nm. Precursor de serotonina y melatonina.',
        'donde_se_encuentra': 'El menos abundante (~1% de residuos). Presente en sitios de unión a sustratos aromáticos. Común en proteínas de membrana (anclas hidrofóbicas). Usado como sonda fluorescente intrínseca de proteínas.',
        'funcion_biologica': 'Precursor de serotonina (neurotransmisor), melatonina (hormona del sueño), vitamina B3 (niacina), auxina (hormona vegetal).',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-indol. Punto isoeléctrico: 5.89. Absorbe UV a 280 nm (el más fuerte). Codificado por 1 codón (UGG).',
        'enfermedades_relacionadas': 'Síndrome de Hartnup (malabsorción). Deficiencia asociada a depresión, insomnio y pelagra.'
    },
    'Y': {
        'nombre': 'Tirosina',
        'abreviatura': 'Tyr',
        'codigo': 'Y',
        'peso_molecular': 181.19,
        'tipo': 'Polar, aromático',
        'hidrofobicidad': 'Baja (-1.3)',
        'carga': 'Neutra',
        'esencial': False,
        'descripcion': 'Aminoácido aromático con grupo hidroxilo. Principal sitio de fosforilación en señalización celular (tirosín quinasas). Precursor de hormonas y pigmentos.',
        'donde_se_encuentra': 'Presente en sitios activos de enzimas. Abundante en receptores de tirosín quinasa (insulina, EGF). Común en proteínas de señalización. En melanina y tiroglobulina.',
        'funcion_biologica': 'Fosforilación de tirosina (señalización), precursor de dopamina, noradrenalina, adrenalina, melanina y hormonas tiroideas (T3, T4).',
        'propiedades_quimicas': 'Cadena lateral: -CH₂-C₆H₄-OH. Punto isoeléctrico: 5.66. pKa del fenol: 10.07. Absorbe UV a 274 nm.',
        'enfermedades_relacionadas': 'Tirosinemia (acumulación tóxica). Albinismo (defecto en tirosinasa). Fenilcetonuria afecta su producción.'
    }
}

PFAM_DESCRIPCIONES = {
    'PF00001': {'nombre': 'Kringle domain', 'descripcion': 'Dominio proteico pequeño con tres bucles disulfuro. Presente en proteínas de coagulación sanguínea y factores de crecimiento. Media interacciones proteína-proteína.', 'tipo': 'Dominio de interacción', 'organismos': 'Vertebrados', 'funcion': 'Unión a factores de crecimiento y proteínas de coagulación'},
    'PF00004': {'nombre': 'ATPase family associated with various cellular activities (AAA)', 'descripcion': 'Dominio AAA+ que hidroliza ATP para generar energía mecánica. Participa en plegamiento, degradación y transporte de proteínas.', 'tipo': 'Dominio enzimático', 'organismos': 'Universal', 'funcion': 'Hidrólisis de ATP, remodelado de proteínas, transporte celular'},
    'PF00005': {'nombre': 'ABC transporter', 'descripcion': 'Dominio de transportadores ABC. Bombas de exportación dependientes de ATP que transportan sustratos diversos a través de membranas.', 'tipo': 'Transportador de membrana', 'organismos': 'Universal', 'funcion': 'Transporte activo de sustratos, resistencia a antibióticos, exportación de toxinas'},
    'PF00006': {'nombre': 'ATP synthase alpha/beta family', 'descripcion': 'Subunidades catalíticas de la ATP sintasa. Convierten gradiente electroquímico en ATP. Esenciales en la fosforilación oxidativa.', 'tipo': 'Enzima energética', 'organismos': 'Universal', 'funcion': 'Síntesis de ATP mediante gradiente de protones'},
    'PF00007': {'nombre': 'Cysteine-rich domain (CRD)', 'descripcion': 'Dominio rico en cisteína con puentes disulfuro. Presente en proteínas de señalización y receptores de superficie celular.', 'tipo': 'Dominio de interacción', 'organismos': 'Eucariotas', 'funcion': 'Unión a ligandos, señalización celular, reconocimiento de patrones'},
    'PF00009': {'nombre': 'Protein kinase domain', 'descripcion': 'Dominio catalítico de quinasas. Transfiere grupo fosfato de ATP a sustratos proteicos. Clave en señalización celular.', 'tipo': 'Dominio enzimático', 'organismos': 'Universal', 'funcion': 'Fosforilación de proteínas, transducción de señales, regulación celular'},
    'PF00010': {'nombre': 'HLH domain', 'descripcion': 'Dominio hélice-loop-hélice. Dominio de dimerización en factores de transcripción. Media unión al ADN.', 'tipo': 'Factor de transcripción', 'organismos': 'Eucariotas', 'funcion': 'Unión al ADN, regulación de la transcripción'},
    'PF00013': {'nombre': 'KH domain', 'descripcion': 'Dominio KH de unión a RNA. Dominio conservado que reconoce secuencias específicas de RNA.', 'tipo': 'Dominio de unión a RNA', 'organismos': 'Universal', 'funcion': 'Unión y procesamiento de RNA, regulación postranscripcional'},
    'PF00014': {'nombre': 'Kunitz/Bovine pancreatic trypsin inhibitor domain', 'descripcion': 'Dominio inhibidor de Kunitz. Inhibe serín proteasas. Presente en inhibidores de proteasa y toxinas.', 'tipo': 'Inhibidor enzimático', 'organismos': 'Animales', 'funcion': 'Inhibición de serín proteasas, regulación de cascadas proteolíticas'},
    'PF00017': {'nombre': 'SH2 domain', 'descripcion': 'Dominio SH2 (Src Homology 2). Reconoce fosfotirosina en proteínas. Esencial en señalización de tirosín quinasas.', 'tipo': 'Dominio de interacción', 'organismos': 'Eucariotas', 'funcion': 'Reconocimiento de fosfotirosina, transducción de señales'},
    'PF00018': {'nombre': 'SH3 domain', 'descripcion': 'Dominio SH3 (Src Homology 3). Reconoce secuencias prolina-ricas (PxxP). Media interacciones proteína-proteína.', 'tipo': 'Dominio de interacción', 'organismos': 'Eucariotas', 'funcion': 'Unión a motivos prolina-ricos, organización de complejos proteicos'},
    'PF00022': {'nombre': 'Actin', 'descripcion': 'Proteína actina. Componente principal del citoesqueleto. Participa en motilidad celular, división y mantenimiento de forma.', 'tipo': 'Proteína estructural', 'organismos': 'Eucariotas', 'funcion': 'Citoesqueleto, motilidad celular, contracción muscular'},
    'PF00023': {'nombre': 'Ankyrin repeat', 'descripcion': 'Repetición de ankirina. Motivo de 33 residuos que media interacciones proteína-proteína. Presente en canales iónicos y señalización.', 'tipo': 'Dominio de repetición', 'organismos': 'Universal', 'funcion': 'Interacciones proteína-proteína, anclaje de membrana, señalización'},
    'PF00025': {'nombre': 'Arf small GTPase', 'descripcion': 'Pequeña GTPasa Arf. Regula el tráfico vesicular y la organización del aparato de Golgi.', 'tipo': 'GTPasa', 'organismos': 'Eucariotas', 'funcion': 'Regulación de tráfico vesicular, modificación lipídica'},
    'PF00028': {'nombre': 'Rubredoxin', 'descripcion': 'Rubredoxina. Proteína de hierro-azufre pequeña que participa en transferencia de electrones.', 'tipo': 'Proteína de transferencia de electrones', 'organismos': 'Bacterias y arqueas', 'funcion': 'Transferencia de electrones, metabolismo anaeróbico'},
    'PF00030': {'nombre': 'Cytochrome c', 'descripcion': 'Citocromo c. Proteína de transferencia de electrones en la cadena respiratoria. Componente esencial de la fosforilación oxidativa.', 'tipo': 'Proteína de transferencia de electrones', 'organismos': 'Universal', 'funcion': 'Transferencia de electrones entre complejos III y IV, apoptosis'},
    'PF00032': {'nombre': 'Cytochrome b', 'descripcion': 'Citocromo b. Componente del complejo bc1 (complejo III) de la cadena respiratoria.', 'tipo': 'Proteína de transferencia de electrones', 'organismos': 'Universal', 'funcion': 'Transferencia de electrones, cadena respiratoria'},
    'PF00034': {'nombre': 'EF-hand', 'descripcion': 'Motivo EF-hand. Dominio de unión a calcio con hélices E y F. Presente en calmodulina y proteínas de señalización Ca²⁺-dependientes.', 'tipo': 'Dominio de unión a calcio', 'organismos': 'Eucariotas', 'funcion': 'Unión a Ca²⁺, señalización calcio-dependiente, regulación enzimática'},
    'PF00038': {'nombre': 'Eukaryotic protein kinase domain', 'descripcion': 'Dominio quinasa eucariota. Cataliza la transferencia de fosfato a serina/treonina/tirosina. Clave en cascadas de señalización.', 'tipo': 'Dominio enzimático', 'organismos': 'Eucariotas', 'funcion': 'Fosforilación, transducción de señales, control del ciclo celular'},
    'PF00041': {'nombre': 'Fn3 domain', 'descripcion': 'Dominio fibronectina tipo 3. Similar a inmunoglobulinas. Media interacciones célula-célula y célula-matriz.', 'tipo': 'Dominio de adhesión', 'organismos': 'Animales', 'funcion': 'Adhesión celular, reconocimiento molecular, señalización'},
    'PF00042': {'nombre': 'DNA-binding domain', 'descripcion': 'Dominio de unión a ADN. Motivo helix-turn-helix que reconoce secuencias específicas de ADN.', 'tipo': 'Factor de transcripción', 'organismos': 'Universal', 'funcion': 'Unión al ADN, regulación de la transcripción'},
    'PF00044': {'nombre': 'Glycosyl transferase', 'descripcion': 'Glicosiltransferasa. Enzima que transfiere azúcares a sustratos proteicos o lipídicos. Esencial en glicosilación.', 'tipo': 'Enzima modificadora', 'organismos': 'Universal', 'funcion': 'Glicosilación de proteínas y lípidos, biosíntesis de glicoconjugados'},
    'PF00047': {'nombre': 'Immunoglobulin domain', 'descripcion': 'Dominio de inmunoglobulina. Estructura sándwich de beta-láminas. Presente en anticuerpos, receptores y proteínas de adhesión.', 'tipo': 'Dominio de reconocimiento', 'organismos': 'Vertebrados', 'funcion': 'Reconocimiento antigénico, adhesión celular, sistema inmunitario'},
    'PF00050': {'nombre': 'Homeodomain', 'descripcion': 'Homeodominio. Factor de transcripción clave en el desarrollo embrionario. Regula la expresión de genes de identidad corporal.', 'tipo': 'Factor de transcripción', 'organismos': 'Eucariotas', 'funcion': 'Regulación del desarrollo, determinación del plan corporal'},
    'PF00055': {'nombre': 'Lactate/malate dehydrogenase', 'descripcion': 'Lactato/malato deshidrogenasa. Enzimas del metabolismo central que catalizan la interconversión de lactato-piruvato y malato-oxaloacetato.', 'tipo': 'Enzima metabólica', 'organismos': 'Universal', 'funcion': 'Metabolismo energético, ciclo de Krebs, fermentación láctica'},
    'PF00056': {'nombre': 'Peptidase M24', 'descripcion': 'Peptidasa M24 (metionina aminopeptidasa). Elimina la metionina N-terminal de proteínas nacientes.', 'tipo': 'Peptidasa', 'organismos': 'Universal', 'funcion': 'Procesamiento N-terminal de proteínas, maduración postraduccional'},
    'PF00059': {'nombre': 'Lectin domain', 'descripcion': 'Dominio de lectina. Reconoce carbohidratos específicos en la superficie celular. Participa en adhesión y señalización.', 'tipo': 'Dominio de unión a carbohidratos', 'organismos': 'Universal', 'funcion': 'Reconocimiento de glicanos, adhesión celular, defensa inmunitaria'},
    'PF00061': {'nombre': 'Lipocalin / cytosolic fatty-acid binding protein family', 'descripcion': 'Lipocalina. Proteína de transporte de lípidos pequeña con barril beta. Transporta moléculas hidrofóbicas.', 'tipo': 'Proteína de transporte', 'organismos': 'Animales', 'funcion': 'Transporte de lípidos, feromonas, retinoides y prostaglandinas'},
    'PF00064': {'nombre': 'Neurotransmitter-gated ion-channel', 'descripcion': 'Canal iónico neurotransmisor-dependiente. Receptores de acetilcolina, GABA y glicina. Media transmisión sináptica rápida.', 'tipo': 'Canal iónico', 'organismos': 'Animales', 'funcion': 'Transmisión sináptica, excitabilidad neuronal'},
    'PF00067': {'nombre': 'Cytochrome P450', 'descripcion': 'Citocromo P450. Familia de monooxigenasas que oxidan sustratos diversos. Clave en detoxificación y metabolismo de fármacos.', 'tipo': 'Enzima oxidativa', 'organismos': 'Universal', 'funcion': 'Detoxificación, metabolismo de fármacos, síntesis de esteroides'},
    'PF00069': {'nombre': 'Protein kinase domain (Ser/Thr)', 'descripcion': 'Dominio quinasa serina/treonina. El dominio más grande en el genoma humano (~500 genes). Clave en señalización celular.', 'tipo': 'Dominio enzimático', 'organismos': 'Eucariotas', 'funcion': 'Fosforilación de Ser/Thr, cascadas de señalización, control del ciclo celular'},
    'PF00071': {'nombre': 'Ras family', 'descripcion': 'Familia Ras. Pequeñas GTPasas que actúan como interruptores moleculares. Mutaciones en Ras causan ~30% de cánceres humanos.', 'tipo': 'GTPasa', 'organismos': 'Eucariotas', 'funcion': 'Señalización de proliferación celular, interruptor molecular GTP/GDP'},
    'PF00072': {'nombre': 'Response regulator receiver domain', 'descripcion': 'Dominio receptor de regulador de respuesta. Componente de sistemas de dos componentes en bacterias.', 'tipo': 'Dominio regulador', 'organismos': 'Bacterias', 'funcion': 'Transducción de señales en sistemas de dos componentes'},
    'PF00073': {'nombre': 'Peroxidase', 'descripcion': 'Peroxidasa. Enzima que reduce peróxido de hidrógeno. Protege contra daño oxidativo.', 'tipo': 'Enzima antioxidante', 'organismos': 'Universal', 'funcion': 'Detoxificación de H₂O₂, defensa antioxidante, biosíntesis de hormonas'},
    'PF00076': {'nombre': 'RNA recognition motif (RRM)', 'descripcion': 'Motivo de reconocimiento de RNA (RRM). El dominio de unión a RNA más común en eucariotas.', 'tipo': 'Dominio de unión a RNA', 'organismos': 'Eucariotas', 'funcion': 'Unión y procesamiento de RNA, splicing, estabilidad de mRNA'},
    'PF00077': {'nombre': 'Ribosomal protein', 'descripcion': 'Proteína ribosomal. Componente del ribosoma, la máquina de síntesis proteica.', 'tipo': 'Proteína ribosomal', 'organismos': 'Universal', 'funcion': 'Traducción, síntesis de proteínas, estructura del ribosoma'},
    'PF00078': {'nombre': 'Metalloprotease', 'descripcion': 'Metaloproteasa. Enzima que degrada péptidos usando un ión metálico (zinc). Participa en remodelado de tejidos.', 'tipo': 'Proteasa', 'organismos': 'Universal', 'funcion': 'Degradación proteica, remodelado de matriz extracelular, procesamiento de hormonas'},
    'PF00082': {'nombre': 'Proteasome subunit', 'descripcion': 'Subunidad del proteasoma. Complejo de degradación proteica ubiquitina-dependiente. Clave en reciclaje de proteínas.', 'tipo': 'Complejo proteolítico', 'organismos': 'Eucariotas y arqueas', 'funcion': 'Degradación proteica regulada, procesamiento de antígenos, control de calidad'},
    'PF00084': {'nombre': 'SNF2-related domain', 'descripcion': 'Dominio SNF2/helicasa. ATPasa de remodelado de cromatina. Regula accesibilidad del ADN.', 'tipo': 'Remodelador de cromatina', 'organismos': 'Eucariotas', 'funcion': 'Remodelado de cromatina, regulación epigenética, reparación de ADN'},
    'PF00085': {'nombre': 'Thioredoxin', 'descripcion': 'Tiorredoxina. Proteína antioxidante que reduce puentes disulfuro. Clave en el mantenimiento del estado redox celular.', 'tipo': 'Proteína antioxidante', 'organismos': 'Universal', 'funcion': 'Reducción de puentes disulfuro, defensa antioxidante, regulación redox'},
    'PF00089': {'nombre': 'Trypsin', 'descripcion': 'Tripsina/serín proteasa. Enzima digestiva que corta proteínas después de residuos básicos. Modelo clásico de catálisis enzimática.', 'tipo': 'Proteasa digestiva', 'organismos': 'Animales', 'funcion': 'Digestión de proteínas, cascadas de coagulación, activación enzimática'},
    'PF00096': {'nombre': 'Zinc finger C2H2', 'descripcion': 'Dedo de zinc C2H2. El dominio de unión al ADN más común en eucariotas. Presente en ~3% de genes humanos.', 'tipo': 'Factor de transcripción', 'organismos': 'Eucariotas', 'funcion': 'Unión al ADN, regulación transcripcional, reconocimiento de secuencias'},
    'PF00107': {'nombre': 'Dehydrogenase', 'descripcion': 'Deshidrogenasa NAD-dependiente. Enzimas centrales del metabolismo energético que catalizan reacciones de oxidación-reducción.', 'tipo': 'Enzima metabólica', 'organismos': 'Universal', 'funcion': 'Metabolismo energético, oxidación de sustratos, ciclo de Krebs'},
    'PF00117': {'nombre': 'SH2 domain (Src)', 'descripcion': 'Dominio SH2 de Src. Variante específica del dominio SH2 en tirosín quinasas de la familia Src.', 'tipo': 'Dominio de interacción', 'organismos': 'Animales', 'funcion': 'Señalización de tirosín quinasa, oncogénesis'},
    'PF00128': {'nombre': 'Alpha/beta hydrolase fold', 'descripcion': 'Plegamiento alfa/beta hidrolasa. Superfamilia enzimática diversa que incluye lipasas, esterasas y epóxido hidrolasas.', 'tipo': 'Enzima hidrolítica', 'organismos': 'Universal', 'funcion': 'Hidrólisis de ésteres, lipasas, detoxificación, metabolismo de lípidos'},
    'PF00149': {'nombre': 'Metallophosphoesterase', 'descripcion': 'Metalofosfoesterasa. Enzima dependiente de metales que hidroliza enlaces fosfato.', 'tipo': 'Enzima fosfatasa', 'organismos': 'Universal', 'funcion': 'Hidrólisis de fosfomonoésteres, procesamiento de nucleótidos'},
    'PF00168': {'nombre': 'C2 domain', 'descripcion': 'Dominio C2. Dominio de unión a calcio y fosfolípidos. Presente en proteínas de señalización y tráfico vesicular.', 'tipo': 'Dominio de unión a membrana', 'organismos': 'Eucariotas', 'funcion': 'Unión a calcio y membrana, señalización, tráfico vesicular'},
    'PF00179': {'nombre': 'Ubiquitin-conjugating enzyme', 'descripcion': 'Enzima conjugadora de ubiquitina (E2). Participa en la ubiquitinación de proteínas para su degradación.', 'tipo': 'Enzima de ubiquitinación', 'organismos': 'Eucariotas', 'funcion': 'Ubiquitinación, marcaje para degradación proteica, regulación celular'},
    'PF00202': {'nombre': 'Glutamine amidotransferase', 'descripcion': 'Glutamina amidotransferasa. Enzima que transfiere el grupo amida de glutamina en biosíntesis de nucleótidos y aminoácidos.', 'tipo': 'Enzima biosintética', 'organismos': 'Universal', 'funcion': 'Biosíntesis de nucleótidos y aminoácidos, metabolismo de nitrógeno'},
    'PF00270': {'nombre': 'Helicase', 'descripcion': 'Helicasa ATP-dependiente. Desenrolla dúplex de ácidos nucleicos. Esencial en replicación, transcripción y reparación de ADN.', 'tipo': 'Enzima de ácidos nucleicos', 'organismos': 'Universal', 'funcion': 'Desenrollamiento de ADN/RNA, replicación, reparación, transcripción'},
    'PF00368': {'nombre': 'Ribosomal protein S5 domain', 'descripcion': 'Dominio de proteína ribosomal S5. Componente de la subunidad menor del ribosoma.', 'tipo': 'Proteína ribosomal', 'organismos': 'Universal', 'funcion': 'Estructura del ribosoma, unión de tRNA, traducción'},
    'PF00400': {'nombre': 'WD40 repeat', 'descripcion': 'Repetición WD40. Motivo beta-propeller que media interacciones proteína-proteína. Muy común en proteínas de señalización.', 'tipo': 'Dominio de repetición', 'organismos': 'Eucariotas', 'funcion': 'Andamiaje de complejos proteicos, señalización, ubiquitinación'},
    'PF00486': {'nombre': 'Adrenodoxin', 'descripcion': 'Adrenodoxina. Proteína ferrosulfurosa que transfiere electrones al citocromo P450 en glándulas suprarrenales.', 'tipo': 'Proteína de transferencia de electrones', 'organismos': 'Animales', 'funcion': 'Transferencia de electrones, síntesis de esteroides'},
    'PF00501': {'nombre': 'AMP-binding enzyme', 'descripcion': 'Enzima de unión a AMP. Familia de enzimas que activan sustratos mediante adenilación.', 'tipo': 'Enzima de activación', 'organismos': 'Universal', 'funcion': 'Activación de ácidos grasos, síntesis de péptidos no ribosomales'},
    'PF00512': {'nombre': 'Histone H2A', 'descripcion': 'Histona H2A. Componente del nucleosoma. Empaqueta el ADN en cromatina y regula su accesibilidad.', 'tipo': 'Proteína de cromatina', 'organismos': 'Eucariotas', 'funcion': 'Empaquetamiento del ADN, regulación epigenética, reparación de ADN'},
    'PF00533': {'nombre': 'BRCT domain', 'descripcion': 'Dominio BRCT. Dominio de interacción en proteínas de respuesta a daño al ADN. Mutado en cáncer de mama.', 'tipo': 'Dominio de respuesta a daño', 'organismos': 'Eucariotas', 'funcion': 'Reparación de ADN, punto de control del ciclo celular'},
    'PF00571': {'nombre': 'CBS domain', 'descripcion': 'Dominio CBS (cistationina beta-sintasa). Dominio regulador que une ATP/AMP. Sensor de energía celular.', 'tipo': 'Dominio regulador', 'organismos': 'Universal', 'funcion': 'Sensor de energía celular (AMP/ATP), regulación de canales iónicos'},
    'PF00627': {'nombre': 'Ubiquitin-associated domain', 'descripcion': 'Dominio UBA (asociado a ubiquitina). Reconoce ubiquitina en proteínas marcadas para degradación.', 'tipo': 'Dominio de reconocimiento', 'organismos': 'Eucariotas', 'funcion': 'Reconocimiento de ubiquitina, degradación proteica'},
    'PF00646': {'nombre': 'F-box domain', 'descripcion': 'Dominio F-box. Componente del complejo SCF (ubiquitina ligasa). Reconoce sustratos para ubiquitinación.', 'tipo': 'Dominio de reconocimiento', 'organismos': 'Eucariotas', 'funcion': 'Reconocimiento de sustratos, ubiquitinación, control del ciclo celular'},
    'PF00931': {'nombre': 'NB-ARC domain', 'descripcion': 'Dominio NB-ARC. Presente en proteínas de resistencia a enfermedades en plantas. Señal de defensa inmunitaria.', 'tipo': 'Dominio de resistencia', 'organismos': 'Plantas', 'funcion': 'Inmunidad innata de plantas, detección de patógenos'},
    'PF01048': {'nombre': 'Preprotein translocase', 'descripcion': 'Translocasa de preproteínas. Canal de membrana para el transporte de proteínas nacientes.', 'tipo': 'Canal de transporte', 'organismos': 'Bacterias', 'funcion': 'Translocación de proteínas a través de membranas, secreción'},
    'PF01246': {'nombre': 'Chromatin organization modifier domain', 'descripcion': 'Dominio CHROMO. Dominio de modificación de cromatina. Reconoce histonas metiladas.', 'tipo': 'Dominio epigenético', 'organismos': 'Eucariotas', 'funcion': 'Reconocimiento de marcas epigenéticas, silenciamiento génico'},
    'PF01370': {'nombre': 'NTP pyrophosphohydrolase', 'descripcion': 'Pirofosfohidrolasa de NTP. Hidroliza nucleótidos trifosfato. Regula niveles de nucleótidos celulares.', 'tipo': 'Enzima hidrolítica', 'organismos': 'Universal', 'funcion': 'Regulación de nucleótidos, control de calidad de mRNA'},
    'PF01583': {'nombre': 'TIR domain', 'descripcion': 'Dominio TIR. Presente en receptores Toll-like y proteínas de inmunidad innata. Media señalización inflamatoria.', 'tipo': 'Dominio inmunitario', 'organismos': 'Animales y plantas', 'funcion': 'Inmunidad innata, detección de patógenos, señalización inflamatoria'},
    'PF01858': {'nombre': 'HEAT repeat', 'descripcion': 'Repetición HEAT. Motivo de repetición alargado que forma superhélices. Media transporte nuclear y tráfico vesicular.', 'tipo': 'Dominio de repetición', 'organismos': 'Eucariotas', 'funcion': 'Transporte nuclear, tráfico vesicular, andamiaje proteico'},
    'PF02013': {'nombre': 'PDZ domain', 'descripcion': 'Dominio PDZ. Reconoce motivos C-terminales en proteínas. Organiza complejos de señalización en la membrana.', 'tipo': 'Dominio de interacción', 'organismos': 'Eucariotas', 'funcion': 'Organización de complejos de señalización, polaridad celular'},
    'PF02198': {'nombre': 'SAM domain', 'descripcion': 'Dominio SAM (Sterile Alpha Motif). Dominio de interacción proteína-proteína en proteínas de señalización.', 'tipo': 'Dominio de interacción', 'organismos': 'Eucariotas', 'funcion': 'Dimerización, regulación transcripcional, desarrollo'},
    'PF02798': {'nombre': 'PIN domain', 'descripcion': 'Dominio PIN. Dominio con actividad ribonucleasa. Participa en procesamiento de RNA y respuesta a estrés.', 'tipo': 'Ribonucleasa', 'organismos': 'Universal', 'funcion': 'Procesamiento de RNA, respuesta a estrés nucleotídico'},
    'PF02811': {'nombre': 'KOW domain', 'descripcion': 'Dominio KOW. Motivo de unión a RNA en proteínas ribosomales y factores de transcripción.', 'tipo': 'Dominio de unión a RNA', 'organismos': 'Universal', 'funcion': 'Unión a RNA, traducción, transcripción'},
    'PF03261': {'nombre': 'DUF389', 'descripcion': 'Dominio de función desconocida 389. Función biológica por determinar.', 'tipo': 'Función desconocida', 'organismos': 'Bacterias', 'funcion': 'No determinada'},
    'PF04034': {'nombre': 'Glyoxalase domain', 'descripcion': 'Dominio glioxalasa. Enzima que detoxifica metilglioxal, un subproducto tóxico del metabolismo.', 'tipo': 'Enzima detoxificante', 'organismos': 'Universal', 'funcion': 'Detoxificación de metilglioxal, defensa contra estrés glucolítico'},
    'PF07679': {'nombre': 'Immunoglobulin I-set domain', 'descripcion': 'Dominio I-set de inmunoglobulina. Variante de Ig presente en moléculas de adhesión celular y receptores.', 'tipo': 'Dominio de adhesión', 'organismos': 'Animales', 'funcion': 'Adhesión celular, reconocimiento molecular, desarrollo neuronal'},
    'PF07714': {'nombre': 'Protein tyrosine kinase', 'descripcion': 'Tirosín quinasa. Fosforila residuos de tirosina. Mutaciones causan cáncer. Dianas terapéuticas principales.', 'tipo': 'Dominio enzimático', 'organismos': 'Animales', 'funcion': 'Fosforilación de tirosina, oncogénesis, diana farmacológica'},
    'PF07716': {'nombre': 'Protein kinase (eukaryotic)', 'descripcion': 'Quinasa eucariota. La familia génica más grande en humanos (~500 genes). Regula prácticamente todos los procesos celulares.', 'tipo': 'Dominio enzimático', 'organismos': 'Eucariotas', 'funcion': 'Fosforilación, señalización celular, diana farmacológica'},
}


def get_pfam_info(familia_id):
    base_id = familia_id.split('.')[0]
    if base_id in PFAM_DESCRIPCIONES:
        return PFAM_DESCRIPCIONES[base_id]
    for key in PFAM_DESCRIPCIONES:
        if base_id.startswith(key):
            return PFAM_DESCRIPCIONES[key]
    return None
