TRADUCCIONES = {
    'es': {
        'page_title': 'Clasificador de Proteinas v3',
        'main_title': 'Clasificador de Familias de Proteinas',
        'main_caption': 'IA para clasificacion de proteinas | 5,513 familias Pfam | Precision: 92% | PyTorch MLP',
        'footer': 'Clasificador de Proteinas v3.0 | PyTorch MLP | 5,513 familias | 92% precision | Dataset: Pfam | Hugging Face Spaces',
        'sidebar_header': 'Panel de Control',
        'model_subtitle': 'Modelo Actual',
        'families': 'Familias',
        'features': 'Features',
        'precision': 'Precision',
        'embeddings': 'Embeddings',
        'no': 'No',
        'search_family': 'Buscar Familia Pfam',
        'family_name': 'Nombre de familia:',
        'family_placeholder': 'PF00001...',
        'no_families_found': 'No se encontraron familias',
        'and_more': '... y {count} mas',
        'search_aa': 'Buscar Aminoacido',
        'aa_code_name': 'Codigo o nombre:',
        'aa_placeholder': 'A, Ala, Alanina...',
        'aa_not_found': 'No encontrado',
        'type_legend': 'Leyenda de tipos:',
        'enter_sequence': 'Ingresa tu secuencia proteica',
        'sequence_label': 'Secuencia de aminoacidos:',
        'sequence_placeholder': 'Ej: MKWVTFISLLFLFSSAYSRGVFRDTHKSEIAHRFKDLGEEHFKGLV...',
        'sequence_help': 'Ingresa la secuencia usando los 20 aminoacidos estandar (A C D E F G H I K L M N P Q R S T V W Y)',
        'analyzed_sequence': 'Secuencia analizada:',
        'length': 'Longitud',
        'approx_weight': 'Peso aprox.',
        'charged': 'Cargados',
        'hydrophobic': 'Hidrofobicos',
        'predict_button': 'Predecir Familia',
        'analyzing': 'Analizando secuencia con IA...',
        'predicted_family': 'Familia Predicha:',
        'confidence': 'Confianza:',
        'family_info': 'Informacion de la familia',
        'name': 'Nombre:',
        'type': 'Tipo:',
        'organisms': 'Organismos:',
        'function': 'Funcion:',
        'family_not_available': 'Informacion detallada de {family} no disponible en la base de datos local.',
        'top5_predictions': 'Top 5 predicciones',
        'family_col': 'Familia',
        'probability_col': 'Probabilidad',
        'enter_to_predict': 'Ingresa una secuencia para predecir',
        'sequence_too_short': 'La secuencia es muy corta (minimo 10 aminoacidos)',
        'composition_analysis': 'Analisis de Composicion',
        'composition_by_aa': 'Composicion por aminoacido',
        'composition_pct': 'Composicion (%)',
        'distribution_by_type': 'Distribucion por tipo',
        'percentage': 'Porcentaje (%)',
        'top5_aa': 'Top 5 aminoacidos presentes',
        'essential': 'Esencial',
        'not_essential': 'No esencial',
        'yes': 'Si',
        'view_full_details': 'Ver detalles completos de todos los aminoacidos presentes',
        'more_info_about': 'Mas info sobre {name}',
        'description': 'Descripcion:',
        'where_found': 'Donde se encuentra:',
        'biological_function': 'Funcion biologica:',
        'chemical_properties': 'Propiedades quimicas:',
        'hydrophobicity': 'Hidrofobicidad:',
        'related_diseases': 'Enfermedades relacionadas:',
        'molecular_weight': 'Peso molecular:',
        'charge': 'Carga:',
        'essential_label': 'Esencial:',
        'aa_total': '{count} aa total',
        'language_label': 'Idioma / Language',
        'nonpolar': 'No polar',
        'polar': 'Polar',
        'positively_charged': 'Cargado positivamente',
        'negatively_charged': 'Cargado negativamente',
        'aromatic': 'Aromatico',
        'special': 'Especial',
    },
    'en': {
        'page_title': 'Protein Classifier v3',
        'main_title': 'Protein Family Classifier',
        'main_caption': 'AI for protein classification | 5,513 Pfam families | Accuracy: 92% | PyTorch MLP',
        'footer': 'Protein Classifier v3.0 | PyTorch MLP | 5,513 families | 92% accuracy | Dataset: Pfam | Hugging Face Spaces',
        'sidebar_header': 'Control Panel',
        'model_subtitle': 'Current Model',
        'families': 'Families',
        'features': 'Features',
        'precision': 'Accuracy',
        'embeddings': 'Embeddings',
        'no': 'No',
        'search_family': 'Search Pfam Family',
        'family_name': 'Family name:',
        'family_placeholder': 'PF00001...',
        'no_families_found': 'No families found',
        'and_more': '... and {count} more',
        'search_aa': 'Search Amino Acid',
        'aa_code_name': 'Code or name:',
        'aa_placeholder': 'A, Ala, Alanine...',
        'aa_not_found': 'Not found',
        'type_legend': 'Type legend:',
        'enter_sequence': 'Enter your protein sequence',
        'sequence_label': 'Amino acid sequence:',
        'sequence_placeholder': 'Ex: MKWVTFISLLFLFSSAYSRGVFRDTHKSEIAHRFKDLGEEHFKGLV...',
        'sequence_help': 'Enter the sequence using the 20 standard amino acids (A C D E F G H I K L M N P Q R S T V W Y)',
        'analyzed_sequence': 'Analyzed sequence:',
        'length': 'Length',
        'approx_weight': 'Approx. weight',
        'charged': 'Charged',
        'hydrophobic': 'Hydrophobic',
        'predict_button': 'Predict Family',
        'analyzing': 'Analyzing sequence with AI...',
        'predicted_family': 'Predicted Family:',
        'confidence': 'Confidence:',
        'family_info': 'Family Information',
        'name': 'Name:',
        'type': 'Type:',
        'organisms': 'Organisms:',
        'function': 'Function:',
        'family_not_available': 'Detailed information for {family} not available in local database.',
        'top5_predictions': 'Top 5 predictions',
        'family_col': 'Family',
        'probability_col': 'Probability',
        'enter_to_predict': 'Enter a sequence to predict',
        'sequence_too_short': 'Sequence is too short (minimum 10 amino acids)',
        'composition_analysis': 'Composition Analysis',
        'composition_by_aa': 'Composition by amino acid',
        'composition_pct': 'Composition (%)',
        'distribution_by_type': 'Distribution by type',
        'percentage': 'Percentage (%)',
        'top5_aa': 'Top 5 amino acids present',
        'essential': 'Essential',
        'not_essential': 'Non-essential',
        'yes': 'Yes',
        'view_full_details': 'View full details of all amino acids present',
        'more_info_about': 'More info about {name}',
        'description': 'Description:',
        'where_found': 'Where found:',
        'biological_function': 'Biological function:',
        'chemical_properties': 'Chemical properties:',
        'hydrophobicity': 'Hydrophobicity:',
        'related_diseases': 'Related diseases:',
        'molecular_weight': 'Molecular weight:',
        'charge': 'Charge:',
        'essential_label': 'Essential:',
        'aa_total': '{count} aa total',
        'language_label': 'Language / Idioma',
        'nonpolar': 'Nonpolar',
        'polar': 'Polar',
        'positively_charged': 'Positively charged',
        'negatively_charged': 'Negatively charged',
        'aromatic': 'Aromatic',
        'special': 'Special',
    },
    'pt': {
        'page_title': 'Classificador de Proteinas v3',
        'main_title': 'Classificador de Familias de Proteinas',
        'main_caption': 'IA para classificacao de proteinas | 5,513 familias Pfam | Precisao: 92% | PyTorch MLP',
        'footer': 'Classificador de Proteinas v3.0 | PyTorch MLP | 5,513 familias | 92% precisao | Dataset: Pfam | Hugging Face Spaces',
        'sidebar_header': 'Painel de Controle',
        'model_subtitle': 'Modelo Atual',
        'families': 'Familias',
        'features': 'Features',
        'precision': 'Precisao',
        'embeddings': 'Embeddings',
        'no': 'Nao',
        'search_family': 'Buscar Familia Pfam',
        'family_name': 'Nome da familia:',
        'family_placeholder': 'PF00001...',
        'no_families_found': 'Nenhuma familia encontrada',
        'and_more': '... e mais {count}',
        'search_aa': 'Buscar Aminoacido',
        'aa_code_name': 'Codigo ou nome:',
        'aa_placeholder': 'A, Ala, Alanina...',
        'aa_not_found': 'Nao encontrado',
        'type_legend': 'Legenda de tipos:',
        'enter_sequence': 'Insira sua sequencia proteica',
        'sequence_label': 'Sequencia de aminoacidos:',
        'sequence_placeholder': 'Ex: MKWVTFISLLFLFSSAYSRGVFRDTHKSEIAHRFKDLGEEHFKGLV...',
        'sequence_help': 'Insira a sequencia usando os 20 aminoacidos padrao (A C D E F G H I K L M N P Q R S T V W Y)',
        'analyzed_sequence': 'Sequencia analisada:',
        'length': 'Comprimento',
        'approx_weight': 'Peso aprox.',
        'charged': 'Carregados',
        'hydrophobic': 'Hidrofobicos',
        'predict_button': 'Prever Familia',
        'analyzing': 'Analisando sequencia com IA...',
        'predicted_family': 'Familia Prevista:',
        'confidence': 'Confianca:',
        'family_info': 'Informacao da Familia',
        'name': 'Nome:',
        'type': 'Tipo:',
        'organisms': 'Organismos:',
        'function': 'Funcao:',
        'family_not_available': 'Informacao detalhada de {family} nao disponivel no banco de dados local.',
        'top5_predictions': 'Top 5 previsoes',
        'family_col': 'Familia',
        'probability_col': 'Probabilidade',
        'enter_to_predict': 'Insira uma sequencia para prever',
        'sequence_too_short': 'A sequencia e muito curta (minimo 10 aminoacidos)',
        'composition_analysis': 'Analise de Composicao',
        'composition_by_aa': 'Composicao por aminoacido',
        'composition_pct': 'Composicao (%)',
        'distribution_by_type': 'Distribuicao por tipo',
        'percentage': 'Porcentagem (%)',
        'top5_aa': 'Top 5 aminoacidos presentes',
        'essential': 'Essencial',
        'not_essential': 'Nao essencial',
        'yes': 'Sim',
        'view_full_details': 'Ver detalhes completos de todos os aminoacidos presentes',
        'more_info_about': 'Mais informacoes sobre {name}',
        'description': 'Descricao:',
        'where_found': 'Onde encontrado:',
        'biological_function': 'Funcao biologica:',
        'chemical_properties': 'Propriedades quimicas:',
        'hydrophobicity': 'Hidrofobicidade:',
        'related_diseases': 'Doencas relacionadas:',
        'molecular_weight': 'Peso molecular:',
        'charge': 'Carga:',
        'essential_label': 'Essencial:',
        'aa_total': '{count} aa total',
        'language_label': 'Idioma / Language',
        'nonpolar': 'Nao polar',
        'polar': 'Polar',
        'positively_charged': 'Carregado positivamente',
        'negatively_charged': 'Carregado negativamente',
        'aromatic': 'Aromatico',
        'special': 'Especial',
    },
    'fr': {
        'page_title': 'Classificateur de Proteines v3',
        'main_title': 'Classificateur de Familles de Proteines',
        'main_caption': 'IA pour la classification des proteines | 5,513 familles Pfam | Precision: 92% | PyTorch MLP',
        'footer': 'Classificateur de Proteines v3.0 | PyTorch MLP | 5,513 familles | 92% precision | Dataset: Pfam | Hugging Face Spaces',
        'sidebar_header': 'Panneau de Controle',
        'model_subtitle': 'Modele Actuel',
        'families': 'Familles',
        'features': 'Features',
        'precision': 'Precision',
        'embeddings': 'Embeddings',
        'no': 'Non',
        'search_family': 'Rechercher Famille Pfam',
        'family_name': 'Nom de famille:',
        'family_placeholder': 'PF00001...',
        'no_families_found': 'Aucune famille trouvee',
        'and_more': '... et {count} de plus',
        'search_aa': 'Rechercher Acide Amine',
        'aa_code_name': 'Code ou nom:',
        'aa_placeholder': 'A, Ala, Alanine...',
        'aa_not_found': 'Non trouve',
        'type_legend': 'Legende des types:',
        'enter_sequence': 'Entrez votre sequence proteique',
        'sequence_label': 'Sequence d\'acides amines:',
        'sequence_placeholder': 'Ex: MKWVTFISLLFLFSSAYSRGVFRDTHKSEIAHRFKDLGEEHFKGLV...',
        'sequence_help': 'Entrez la sequence avec les 20 acides amines standard (A C D E F G H I K L M N P Q R S T V W Y)',
        'analyzed_sequence': 'Sequence analysee:',
        'length': 'Longueur',
        'approx_weight': 'Poids approx.',
        'charged': 'Charges',
        'hydrophobic': 'Hydrophobes',
        'predict_button': 'Predire Famille',
        'analyzing': 'Analyse de la sequence avec l\'IA...',
        'predicted_family': 'Famille Predite:',
        'confidence': 'Confiance:',
        'family_info': 'Informations sur la Famille',
        'name': 'Nom:',
        'type': 'Type:',
        'organisms': 'Organismes:',
        'function': 'Fonction:',
        'family_not_available': 'Informations detaillees pour {family} non disponibles dans la base locale.',
        'top5_predictions': 'Top 5 predictions',
        'family_col': 'Famille',
        'probability_col': 'Probabilite',
        'enter_to_predict': 'Entrez une sequence pour predire',
        'sequence_too_short': 'La sequence est trop courte (minimum 10 acides amines)',
        'composition_analysis': 'Analyse de Composition',
        'composition_by_aa': 'Composition par acide amine',
        'composition_pct': 'Composition (%)',
        'distribution_by_type': 'Distribution par type',
        'percentage': 'Pourcentage (%)',
        'top5_aa': 'Top 5 acides amines presents',
        'essential': 'Essentiel',
        'not_essential': 'Non essentiel',
        'yes': 'Oui',
        'view_full_details': 'Voir les details complets de tous les acides amines presents',
        'more_info_about': 'Plus d\'infos sur {name}',
        'description': 'Description:',
        'where_found': 'Ou se trouve:',
        'biological_function': 'Fonction biologique:',
        'chemical_properties': 'Proprietes chimiques:',
        'hydrophobicity': 'Hydrophobicite:',
        'related_diseases': 'Maladies liees:',
        'molecular_weight': 'Poids moleculaire:',
        'charge': 'Charge:',
        'essential_label': 'Essentiel:',
        'aa_total': '{count} aa total',
        'language_label': 'Langue / Language',
        'nonpolar': 'Non polaire',
        'polar': 'Polaire',
        'positively_charged': 'Charge positivement',
        'negatively_charged': 'Charge negativement',
        'aromatic': 'Aromatique',
        'special': 'Special',
    },
    'de': {
        'page_title': 'Protein-Klassifikator v3',
        'main_title': 'Proteinfamilien-Klassifikator',
        'main_caption': 'KI zur Proteinklassifikation | 5.513 Pfam-Familien | Genauigkeit: 92% | PyTorch MLP',
        'footer': 'Protein-Klassifikator v3.0 | PyTorch MLP | 5.513 Familien | 92% Genauigkeit | Dataset: Pfam | Hugging Face Spaces',
        'sidebar_header': 'Kontrollpanel',
        'model_subtitle': 'Aktuelles Modell',
        'families': 'Familien',
        'features': 'Features',
        'precision': 'Genauigkeit',
        'embeddings': 'Embeddings',
        'no': 'Nein',
        'search_family': 'Pfam-Familie suchen',
        'family_name': 'Familienname:',
        'family_placeholder': 'PF00001...',
        'no_families_found': 'Keine Familien gefunden',
        'and_more': '... und {count} weitere',
        'search_aa': 'Aminosaeure suchen',
        'aa_code_name': 'Code oder Name:',
        'aa_placeholder': 'A, Ala, Alanin...',
        'aa_not_found': 'Nicht gefunden',
        'type_legend': 'Typ-Legende:',
        'enter_sequence': 'Geben Sie Ihre Proteinsequenz ein',
        'sequence_label': 'Aminosaeuresequenz:',
        'sequence_placeholder': 'Bsp: MKWVTFISLLFLFSSAYSRGVFRDTHKSEIAHRFKDLGEEHFKGLV...',
        'sequence_help': 'Geben Sie die Sequenz mit den 20 Standard-Aminosaeuren ein (A C D E F G H I K L M N P Q R S T V W Y)',
        'analyzed_sequence': 'Analysierte Sequenz:',
        'length': 'Laenge',
        'approx_weight': 'Gewicht ca.',
        'charged': 'Geladen',
        'hydrophobic': 'Hydrophob',
        'predict_button': 'Familie vorhersagen',
        'analyzing': 'Sequenz wird mit KI analysiert...',
        'predicted_family': 'Vorhergesagte Familie:',
        'confidence': 'Konfidenz:',
        'family_info': 'Familieninformationen',
        'name': 'Name:',
        'type': 'Typ:',
        'organisms': 'Organismen:',
        'function': 'Funktion:',
        'family_not_available': 'Detaillierte Informationen fuer {family} in lokaler Datenbank nicht verfuegbar.',
        'top5_predictions': 'Top 5 Vorhersagen',
        'family_col': 'Familie',
        'probability_col': 'Wahrscheinlichkeit',
        'enter_to_predict': 'Geben Sie eine Sequenz zur Vorhersage ein',
        'sequence_too_short': 'Sequenz ist zu kurz (mindestens 10 Aminosaeuren)',
        'composition_analysis': 'Zusammensetzungsanalyse',
        'composition_by_aa': 'Zusammensetzung nach Aminosaeure',
        'composition_pct': 'Zusammensetzung (%)',
        'distribution_by_type': 'Verteilung nach Typ',
        'percentage': 'Prozentsatz (%)',
        'top5_aa': 'Top 5 vorhandene Aminosaeuren',
        'essential': 'Essenziell',
        'not_essential': 'Nicht essenziell',
        'yes': 'Ja',
        'view_full_details': 'Vollstaendige Details aller vorhandenen Aminosaeuren anzeigen',
        'more_info_about': 'Mehr Infos ueber {name}',
        'description': 'Beschreibung:',
        'where_found': 'Vorkommen:',
        'biological_function': 'Biologische Funktion:',
        'chemical_properties': 'Chemische Eigenschaften:',
        'hydrophobicity': 'Hydrophobizitaet:',
        'related_diseases': 'Zugehoerige Krankheiten:',
        'molecular_weight': 'Molekulargewicht:',
        'charge': 'Ladung:',
        'essential_label': 'Essenziell:',
        'aa_total': '{count} aa gesamt',
        'language_label': 'Sprache / Language',
        'nonpolar': 'Unpolar',
        'polar': 'Polar',
        'positively_charged': 'Positiv geladen',
        'negatively_charged': 'Negativ geladen',
        'aromatic': 'Aromatisch',
        'special': 'Speziell',
    },
}

IDIOMAS_NOMBRES = {
    'es': 'Espanol',
    'en': 'English',
    'pt': 'Portugues',
    'fr': 'Francais',
    'de': 'Deutsch',
}

IDIOMAS_OPCIONES = {f"{code} - {name}": code for code, name in IDIOMAS_NOMBRES.items()}


def t(key, lang='es', **kwargs):
    texto = TRADUCCIONES.get(lang, TRADUCCIONES['es']).get(key, key)
    if kwargs:
        try:
            texto = texto.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return texto
